apiVersion: velero.io/v1
kind: Backup
metadata:
  name: mysql-persistent
  labels:
    velero.io/storage-location: default
  namespace: oadp-operator
spec:
  hooks: {}
  includedNamespaces:
  - mysql-persistent
  storageLocation: velero-1
  ttl: 720h0m0s
