apiVersion: oadp.openshift.io/v1alpha1
kind: Velero
metadata:
  name: example-velero
  namespace: oadp-operator
spec:
  olm_managed: true
  use_upstream_images: true
  backupStorageLocations:
    - config:
        insecureSkipTLSVerify: 'true'
        profile: default
        region: noobaa
        s3ForcePathStyle: 'true'
        s3Url: 'https://s3-openshift-storage.apps.ocp4.example.com/'
      credentials_secret_ref:
        name: cloud-credentials
        namespace: oadp-operator
      name: default          
      objectStorage:
        bucket: bkpstorage-338576a4-7770-4de5-bac4-d142dbb57da7
        prefix: velero
      provider: aws
  defaultVeleroPlugins:
    - aws
    - csi
    - openshift
  enableRestic: true
  veleroFeatureFlags:
    - EnableCSI
  volumeSnapshotLocations:
    - config:
        profile: default
        region: noobaa
      provider: aws




apiVersion: oadp.openshift.io/v1alpha1
kind: Velero
metadata:
  name: example-velero
  namespace: openshift-adp
spec:
  olm_managed: true
  use_upstream_images: true
  backupStorageLocations:
    - config:
        insecureSkipTLSVerify: 'true'
        profile: default
        region: noobaa
        s3ForcePathStyle: 'true'
        s3Url: 'https://s3-openshift-storage.apps.ocp4.example.com/'
      credential:
        name: cloud-credentials
        key: cloud          
      objectStorage:
        bucket: veleroobc-4f44dc3b-5737-4b53-91fa-844974d3bec4
        prefix: velero
      provider: aws
  defaultVeleroPlugins:
    - aws
    - csi
    - openshift
  enableRestic: true
  veleroFeatureFlags:
    - EnableCSI
  volumeSnapshotLocations:
    - config:
        profile: default
        region: noobaa
      provider: aws
      
      
      
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: dpa-sample
spec:
  configuration:
    velero:
      defaultPlugins:
      - openshift
      - aws
    restic:
      enable: true
  backupLocations: 
    default: true
    - name: default
      velero:       
        config:
          insecureSkipTLSVerify: 'true'
          profile: default
          region: noobaa
          s3ForcePathStyle: 'true'
          s3Url: 'https://s3-openshift-storage.apps.ocp4.example.com/'
        credential:
          name: cloud-credentials
          key: cloud          
        objectStorage:
          bucket: veleroobc-4f44dc3b-5737-4b53-91fa-844974d3bec4
          prefix: velero
        provider: aws
  snapshotLocations:
    - name: default
      velero:
        provider: aws
        config:
          region: noobaa
          profile: "default"
    default: true     
